[project]
name = "goiener-v7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.1",
    "pandas>=2.3.3",
    "polars>=1.36.1",
    "zstandard>=0.25.0",
]
